version: "3.8"
services:
  mco-worker-service:
    image: mco-worker-service
    depends_on:
      - mco-redis
    volumes:
      - .:/app
  mco-redis:
    image: redis
    command: redis-server
    volumes:
      - ./docker-volumes/redis:/data
    ports:
      - 6379:6379
networks:
  default:
    external:
      name: mco-network
