version: "3.8"
services:
    pg-mco-client:
        image: amacneil/dbmate
        container_name: pg-mco-client
        entrypoint: /bin/sh
        depends_on:
            - pg-mco-server
        volumes:
            - ./db:/db
        environment:
            DATABASE_URL: "postgres://test:welcome123@pg-mco-server:5432/pg-mco?sslmode=disable"
    pg-mco-server:
        image: postgres
        container_name: pg-mco-server
        volumes:
            - ./docker-volumes/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: welcome123
            POSTGRES_DB: pg-mco
        command: -p 5432
networks:
    default:
        external:
            name: mco-network
